# Generated by Django 3.2.11 on 2022-01-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.JSONField(default=dict),
        ),
    ]
