# Generated by Django 3.2.11 on 2022-02-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statuses',
            field=models.CharField(
                choices=[('being_processed', 'Оформляется'), ('on_the_way', 'В пути'), ('delivered', 'Доставлен')],
                default='being_processed', max_length=20),
        ),
    ]
