# Generated by Django 3.2.11 on 2022-02-01 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_order_statuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statuses',
            new_name='status',
        ),
    ]
